name: Fittrek CD

on:
  push:
    branches:
      - fittrek-development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/fittrek

            git pull origin fittrek-development

            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs

            npm ci
            npm run build

            pkill -f "next start" || true
            nohup npm start > app.log 2>&1 &